# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'IOTDemoReminder' do
    pod 'SVProgressHUD', '1.1.3'
    pod 'MBProgressHUD', '~> 0.8'    
end

target 'IOTDemoReminderTests' do

end

